const TYPES = {
  TASKLIST_CREATE: 'TASKLIST_CREATE',
  TASKLIST_DELETE: 'TASKLIST_DELETE',
  TASKLIST_UPDATE: 'TASKLIST_UPDATE',

  TASK_CREATE: 'TASK_CREATE',
  TASK_UPDATE: 'TASK_UPDATE',
  TASK_DELETE: 'TASK_DELETE',

  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  LOG_OUT: 'LOG_OUT',

  TOGGLE_LOADING: 'TOGGLE_LOADING',
};

export default TYPES;
